services:

  deepstream-yolo-face:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEEPSTREAM_VERSION: "7.1"
    image: deepstream-yolo-face:latest
    container_name: deepstream-yolo-face
    
    privileged: true
    # GPU access
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, video, compute, utility]
    
    # Environment variables
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY:-:0}
      #- QT_X11_NO_MITSHM=1
      - CUDA_VISIBLE_DEVICES=0
      - KAFKA_BROKER=kafka:29092
    
    # For GUI display (X11 forwarding)
    volumes:
      - /usr/lib/wsl/lib/:/usr/lib/wsl/lib/:ro # For WSL2 (adjust as needed)
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./models:/app/models:rw
      - ./videos:/app/videos:ro
      - ./outputs:/app/outputs:rw
      #- ./outputs:/app/DeepStream-Yolo-Face/outputs
      - ./src:/app/DeepStream-Yolo-Face:rw
      - ./configs:/app/configs:ro
      - ./tests:/app/tests
    
    # Use network instead of host mode to enable Kafka communication
    networks:
      - deepstream-network
    
    # Interactive mode
    stdin_open: true
    tty: true
    
    # Shared memory for GStreamer
    shm_size: "2gb"
    
    
    # Working directory
    working_dir: /app/DeepStream-Yolo-Face
    
    # Default command - override with docker-compose run
    command: >
       python3 deepstream.py 
       -s file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_1080p_h264.mp4 
       -c /app/configs/config_infer_primary_yoloV8_face.txt
       --kafka-broker kafka:29092

  # Development service with shell access
  dev:
    extends:
      service: deepstream-yolo-face
    container_name: deepstream-yolo-face-dev
    profiles:
      - dev
    entrypoint: ["tail", "-f", "/dev/null"]
    command: []

  triton:
    image: nvcr.io/nvidia/tritonserver:24.12-py3 #25.12-py3 #26.01-py3
    container_name: ds-triton
    profiles:
      - dev
    runtime: nvidia
    ports:
      - "8000:8000"  # HTTP
      - "8001:8001"  # gRPC
      - "8002:8002"  # Metrics
    volumes:
      - ./model-repo:/models
      - ./triton:/app
    command: [
      "tritonserver",
      "--model-repository=/models",
      "--log-verbose=1"
    ]
    #command: ["tail", "-f", "/dev/null"]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    healthcheck:
      test: ["CMD", "curl -f http://localhost:8000/v2/health/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - deepstream-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: ds-zookeeper
    profiles:
      - dev
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    
    # ports:
    #   - "2181:2181"
    networks:
      - deepstream-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: ds-kafka
    profiles:
      - dev
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    #   - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    networks:
      - deepstream-network

networks:
  deepstream-network:
    driver: bridge
